version: '3.8'

services:
  shreds-subscribe:
    build: .
    container_name: shreds-subscribe
    ports:
      - "${UDP_PORT:-18888}:${UDP_PORT:-18888}/udp"  # UDP port for shred stream
      - "${RPC_PORT:-12345}:${RPC_PORT:-12345}"       # RPC port
    environment:
      - UDP_PORT=${UDP_PORT:-18888}
      - RPC_PORT=${RPC_PORT:-12345}
      - TRACE_LOG_PATH
      - RUST_LOG
    volumes:
      - ./logs:/app/logs    # Mount logs directory for trace logs
    restart: unless-stopped
    networks:
      - solana-network

networks:
  solana-network:
    driver: bridge
